[project]
name = "funding-research-app"
version = "0.2.9"
description = "A research funding analysis and collaboration matching tool."
authors = [
    {name = "User", email = "user@example.com"},
]
dependencies = [
    "llm-client",
    "streamlit",
    "beautifulsoup4",
    "httpx",
    "chromadb",
    "sqlalchemy",
    "pytest",
    "pydantic",
    "python-dotenv",
    "ddgs",
    "linkedin_api",
    "pydantic-settings"
]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
