[project]
name = "funding-research-app"
version = "0.4.7"
description = "A research funding analysis and collaboration matching tool."
authors = [
    {name = "User", email = "user@example.com"},
]
dependencies = [
    "llm-client",
    "streamlit",
    "beautifulsoup4",
    "httpx",
    "chromadb",
    "sqlalchemy",
    "pytest",
    "pydantic",
    "python-dotenv",
    "ddgs",
    "linkedin_api",
    "pydantic-settings",
    "geopy",
    "pydeck"
]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = false
ignore-setters = false
fail-under = 95
exclude = ["setup.py", "docs", "build", "tests", "venv", ".venv", "app/main.py", "app/ui", "app/utils/fit_explorer.py"]
ignore-regex = ["^get$", "^mock_.*", ".*Base$"]
verbose = 2
quiet = false
whitelist-regex = []
color = true
omit-covered-files = false
